#
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - livefire_siteb_vars.yml
  tasks:
    - name: Create Transport Node Profiles for cluster at Site-B
      nsxt_transport_node_profiles:
        hostname: "{{ nsx_node1.mgmt_ip }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        resource_type: TransportNodeProfile
        display_name: "{{ item.display_name }}"
        description: "{{ item.description }}"
        host_switch_spec:
          resource_type: StandardHostSwitchSpec
          host_switches: "{{ item.host_switches }}"
        transport_zone_endpoints: "{{ item.transport_zone_endpoints }}"
        state: "{{ state }}"
      with_items:
        - "{{ transport_node_profiles }}"

    - name: Attach Transport node profile to cluster at Site-B
      nsxt_transport_node_collections:
        hostname: "{{ nsx_node1.mgmt_ip }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        display_name: "TNCSITEB"
        resource_type: "TransportNodeCollection"
        description: "Transport Node Collections Hosts"
        compute_manager_name: "{{compute_managers[0].display_name}}"
        cluster_name: "Cluster-01b"
        transport_node_profile_name: "{{transport_node_profiles[0].display_name}}"
        state: present
