#
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - livefire_siteb_vars.yml
  tasks:
    - name: Create VLAN logical switches for Edge Nodes at Site B
      nsxt_logical_switches:
        hostname: "{{ nsx_node1.mgmt_ip }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        display_name: "{{ item.display_name }}"
        replication_mode: SOURCE
        admin_state: UP
        transport_zone_name: "{{ item.transport_zone_name }}"
        uplink_teaming_policy_name: "{{ item.uplink_teaming_policy_name }}"
        vlan: "{{ item.vlan }}"
        state: "{{ state }}"
      with_items:
        - "{{ logical_switches }}"

